name: Biome
main: net.llamaslayers.minecraft.biome.BiomePlugin
version: 0.3.1
description: Change biomes anywhere in any world.
load: startup
commands:
  biome:
    usage: /biome <set <type>|get|list|clear|set-selection <type>|clear-selection>